"""rename infraction columns to english

Revision ID: 955b20503ea5
Revises: e947d644e130
Create Date: 2026-04-06 16:24:10.285005

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '955b20503ea5'
down_revision: Union[str, Sequence[str], None] = 'e947d644e130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infractions', sa.Column('infraction_notice_number', sa.String(), nullable=False))
    op.add_column('infractions', sa.Column('infraction_code', sa.String(), nullable=False))
    op.add_column('infractions', sa.Column('description', sa.String(), nullable=False))
    op.add_column('infractions', sa.Column('infraction_key', sa.String(), nullable=False))
    op.add_column('infractions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('infractions', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('infractions', sa.Column('due_date', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('issuing_authority', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('competent_authority', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('ait_number', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('notification_date', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('defense_deadline', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('offender_indication_deadline', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('fine_amount', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('measurement_taken', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('considered_value', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('regulated_limit', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('infraction_location', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('infraction_date', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('infraction_time', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('city', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('state', sa.String(), nullable=True))
    op.drop_column('infractions', 'medicao_realizada')
    op.drop_column('infractions', 'orgao_competente')
    op.drop_column('infractions', 'data_vencimento')
    op.drop_column('infractions', 'chave_infracao')
    op.drop_column('infractions', 'codigo_infracao')
    op.drop_column('infractions', 'local_infracao')
    op.drop_column('infractions', 'valor_total')
    op.drop_column('infractions', 'orgao_autuador')
    op.drop_column('infractions', 'municipio')
    op.drop_column('infractions', 'auto_infracao')
    op.drop_column('infractions', 'data_infracao')
    op.drop_column('infractions', 'descricao')
    op.drop_column('infractions', 'limite_regulamentado')
    op.drop_column('infractions', 'uf')
    op.drop_column('infractions', 'data_limite_indicacao_infrator')
    op.drop_column('infractions', 'situacao')
    op.drop_column('infractions', 'hora_infracao')
    op.drop_column('infractions', 'numero_ait')
    op.drop_column('infractions', 'valor_considerado')
    op.drop_column('infractions', 'data_notificacao')
    op.drop_column('infractions', 'valor_multa')
    op.drop_column('infractions', 'data_limite_defesa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infractions', sa.Column('data_limite_defesa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('valor_multa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('data_notificacao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('valor_considerado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('numero_ait', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('hora_infracao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('situacao', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('infractions', sa.Column('data_limite_indicacao_infrator', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('uf', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('limite_regulamentado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('infractions', sa.Column('data_infracao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('auto_infracao', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('infractions', sa.Column('municipio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('orgao_autuador', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('valor_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('infractions', sa.Column('local_infracao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('codigo_infracao', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('infractions', sa.Column('chave_infracao', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('infractions', sa.Column('data_vencimento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('orgao_competente', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infractions', sa.Column('medicao_realizada', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('infractions', 'state')
    op.drop_column('infractions', 'city')
    op.drop_column('infractions', 'infraction_time')
    op.drop_column('infractions', 'infraction_date')
    op.drop_column('infractions', 'infraction_location')
    op.drop_column('infractions', 'regulated_limit')
    op.drop_column('infractions', 'considered_value')
    op.drop_column('infractions', 'measurement_taken')
    op.drop_column('infractions', 'fine_amount')
    op.drop_column('infractions', 'offender_indication_deadline')
    op.drop_column('infractions', 'defense_deadline')
    op.drop_column('infractions', 'notification_date')
    op.drop_column('infractions', 'ait_number')
    op.drop_column('infractions', 'competent_authority')
    op.drop_column('infractions', 'issuing_authority')
    op.drop_column('infractions', 'due_date')
    op.drop_column('infractions', 'total_amount')
    op.drop_column('infractions', 'status')
    op.drop_column('infractions', 'infraction_key')
    op.drop_column('infractions', 'description')
    op.drop_column('infractions', 'infraction_code')
    op.drop_column('infractions', 'infraction_notice_number')
    # ### end Alembic commands ###
