"""add new rows to infractions table

Revision ID: 967ce1e2cc57
Revises: 99e71687c3fd
Create Date: 2026-04-09 14:58:27.533509

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '967ce1e2cc57'
down_revision: Union[str, Sequence[str], None] = '99e71687c3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('company_cnpj', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.add_column('infractions', sa.Column('driver_name', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('driver_cnh', sa.String(), nullable=True))
    op.add_column('infractions', sa.Column('driver_document', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('infractions', 'driver_document')
    op.drop_column('infractions', 'driver_cnh')
    op.drop_column('infractions', 'driver_name')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
