"""create initial tables

Revision ID: e947d644e130
Revises: 
Create Date: 2026-04-06 13:30:36.333714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e947d644e130'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('infraction_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('queried_at', sa.DateTime(), nullable=True),
    sa.Column('total_infractions', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infraction_queries_id'), 'infraction_queries', ['id'], unique=False)
    op.create_table('infractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('details_fetched', sa.Boolean(), nullable=True),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('auto_infracao', sa.String(), nullable=False),
    sa.Column('codigo_infracao', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('chave_infracao', sa.String(), nullable=False),
    sa.Column('situacao', sa.String(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.String(), nullable=True),
    sa.Column('orgao_autuador', sa.String(), nullable=True),
    sa.Column('orgao_competente', sa.String(), nullable=True),
    sa.Column('numero_ait', sa.String(), nullable=True),
    sa.Column('data_notificacao', sa.String(), nullable=True),
    sa.Column('data_limite_defesa', sa.String(), nullable=True),
    sa.Column('data_limite_indicacao_infrator', sa.String(), nullable=True),
    sa.Column('valor_multa', sa.String(), nullable=True),
    sa.Column('medicao_realizada', sa.String(), nullable=True),
    sa.Column('valor_considerado', sa.String(), nullable=True),
    sa.Column('limite_regulamentado', sa.String(), nullable=True),
    sa.Column('local_infracao', sa.String(), nullable=True),
    sa.Column('data_infracao', sa.String(), nullable=True),
    sa.Column('hora_infracao', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['infraction_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infractions_id'), 'infractions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infractions_id'), table_name='infractions')
    op.drop_table('infractions')
    op.drop_index(op.f('ix_infraction_queries_id'), table_name='infraction_queries')
    op.drop_table('infraction_queries')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
