from sqlalchemy import Column, Integer, String, Boolean, Float, ForeignKey
from app.core.database import Base

class Infractions(Base):
    __tablename__ = "infractions"
    id = Column(Integer, primary_key=True, index=True)
    query_id = Column(Integer, ForeignKey("infraction_queries.id"), nullable=False)
    details_fetched = Column(Boolean, default=False)
    plate = Column(String, nullable=False)
    infraction_notice_number = Column(String, nullable=False)
    infraction_code = Column(String, nullable=False)
    description = Column(String, nullable=False)
    infraction_key = Column(String, nullable=False)
    status = Column(String, nullable=False)
    total_amount = Column(Float, nullable=False)
    due_date = Column(String, nullable=True)
    issuing_authority = Column(String, nullable=True)
    competent_authority = Column(String, nullable=True)
    ait_number = Column(String, nullable=True)
    notification_date = Column(String, nullable=True)
    defense_deadline = Column(String, nullable=True)
    offender_indication_deadline = Column(String, nullable=True)
    driver_name = Column(String, nullable=True)
    driver_cnh = Column(String, nullable=True)
    driver_document = Column(String, nullable=True)
    fine_amount = Column(String, nullable=True)
    measurement_taken = Column(String, nullable=True)
    considered_value = Column(String, nullable=True)
    regulated_limit = Column(String, nullable=True)
    infraction_location = Column(String, nullable=True)
    infraction_date = Column(String, nullable=True)
    infraction_time = Column(String, nullable=True)
    city = Column(String, nullable=True)
    state = Column(String, nullable=True)