class SenatranDetailsDTO:
    def __init__(self, data: dict):
        self.issuing_authority = data["data"][0]["autuacao"]["orgao_autuador"]
        self.competent_authority = data["data"][0]["autuacao"]["orgao_competente"]
        self.ait_number = data["data"][0]["autuacao"]["numero_ait"]
        self.notification_date = data["data"][0]["autuacao"]["data_notificacao"]
        self.defense_deadline = data["data"][0]["autuacao"]["data_limite_defesa"]
        self.offender_indication_deadline = data["data"][0]["autuacao"]["data_limite_indicacao_infrator"]
        self.driver_name = data["data"][0]["condutor"]["nome"]
        self.driver_cnh = data["data"][0]["condutor"]["cnh"]
        self.driver_document = data["data"][0]["condutor"]["documento"]
        self.fine_amount = data["data"][0]["infracao"]["valor_multa"]
        self.measurement_taken = data["data"][0]["infracao"]["medicao_realizada"]
        self.considered_value = data["data"][0]["infracao"]["valor_considerado"]
        self.regulated_limit = data["data"][0]["infracao"]["limite_regulamentado"]
        self.infraction_location = data["data"][0]["local_data_hora"]["local_infracao"]
        self.infraction_date = data["data"][0]["local_data_hora"]["data_infracao"]
        self.infraction_time = data["data"][0]["local_data_hora"]["hora_infracao"]
        self.city = data["data"][0]["local_data_hora"]["municipio"]
        self.state = data["data"][0]["local_data_hora"]["uf"]
